services:
  vsce:
    container_name: vsce
    hostname: vsce
    build: .
    image: ghcr.io/nchekwa/vsce:latest
    ports:
      - 8080:8080
    volumes:
      - ./config/:/home/coder/.config
      - ./project/:/home/coder/project
    user: "${UID}:${GID}"
    environment:
      DOCKER_USER: $USER
      PASSWORD: ${PASSWORD:-vsce}
      INSTALL_EXTENSIONS_FORCE: ${INSTALL_EXTENSIONS_FORCE:-false}
      EXTENSIONS_UPDATE: ${EXTENSIONS_UPDATE:-true}
      INSTALL_EXTENSIONS: |
        ms-python.flake8
        ms-python.pylint
        redhat.vscode-yaml
        ms-python.python
        ms-azuretools.vscode-docker
        ms-azuretools.vscode-containers
        kilocode.kilo-code
      INSTALL_DPKG: |
        curl
        git
        jq
      INSTALL_NPM: |
        @anthropic-ai/claude-code
        @proofs-io/shotgun
        @proofs-io/shotgun-server
    stdin_open: true
    tty: true